FROM python:3.8.6-slim-buster

ADD . /TestApp

WORKDIR /TestApp

ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=127.0.0.1

#RUN apk add --no-cache gcc musl-dev linux-headers
#RUN apk --update add build-base jpeg-dev zlib-dev
#RUN apk add py3-requests py-pip libffi-dev openssl-dev libc-dev make
#
#RUN apt-get install build-base jpeg-dev zlib-dev
#RUN apt-get install gcc musl-dev linux-headers
#RUN apt-get install py3-requests py-pip libffi-dev openssl-dev libc-dev make

COPY requirements.txt requirements.txt

# RUN sudo pip install requests
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

COPY . .

CMD ["flask", "run"]